org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=GreatDani
plugin_name=GridCraft
plugin_description=A Crafting mod.
plugin_author=GreatDani
plugin_version=0.3.5
plugin_website=
plugin_main_entrypoint=com.greatdani.craftingplugin.CraftingPlugin
server_version=*
